# This workflow will install Python dependencies and run tests using Python unittest

name: run Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        # add python 3.6 when the problem with installing it on ubuntu-latest gets fixed

    steps:
    - name: Check out repo 
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install python-igraph numpy matplotlib scipy geopy
    - name: Run tests
      run: |
        python -m unittest discover -p '*_tests.py'
